#! /usr/bin/python

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with and, the first terms will be: 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

f = [1,2]

while(f[-1] + f[-2]) <= 4000000:
  f.append(f[-1] + f[-2])

g = [i for i in f if i%2 == 0]
print(sum(g))
